MODEL:
  DEVICE: 'cuda'
  BACKBONE: 'cnn'
  NAME: 'resnet50'
  PRETRAIN_PATH: '/mnt/Storage/checkpoints/resnet50-19c8e357.pth'
  CENTER_LOSS: False
  WEIGHT_REGULARIZED_TRIPLET: True

DATASETS:
  NAMES: 'ASRD'
  ROOT_DIR: '/home/gxy/文档/ASRD'

DATALOADER:
  FOLD: 5
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 100
  BASE_LR: 1e-2
  STEPS: [30, 60]
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  CHECKPOINT_PERIOD: 90
  LOG_PERIOD: 20
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 64
  LR_SCHEDULER: 'warmup'

TEST:
  EVAL_ONLY: False
  IMS_PER_BATCH: 256
